const data=[
{id:1,n:'Dom Seniora Zielona Przystań',c:'Warszawa',r:'mazowieckie',lat:52.167,lng:21.09,d:12,p:7200,s:4.9,o:84,a:'2 miejsca',care:['Całodobowa','Medyczna'],x:['Rehabilitacja','Diety','Pokój 1-os.','Ogród'],color:'#bdcfaa'},
{id:2,n:'Rezydencja Pod Lipami',c:'Kraków',r:'małopolskie',lat:50.034,lng:19.93,d:18,p:6800,s:4.8,o:61,a:'1 miejsce',care:['Całodobowa','Paliatywna'],x:['Diety','Pokój 1-os.','Ogród'],color:'#dfb49f'},
{id:3,n:'Przystań Dobra Jesień',c:'Gdańsk',r:'pomorskie',lat:54.365,lng:18.58,d:9,p:8100,s:4.9,o:47,a:'od 15.09',care:['Całodobowa','Medyczna'],x:['Rehabilitacja','Diety','Ogród'],color:'#a9c9d2'},
{id:4,n:'Centrum Opieki Harmonia',c:'Wrocław',r:'dolnośląskie',lat:51.096,lng:17.08,d:25,p:6400,s:4.7,o:93,a:'3 miejsca',care:['Całodobowa','Medyczna','Paliatywna'],x:['Rehabilitacja','Pokój 1-os.'],color:'#d7c69f'},
{id:5,n:'Klub Seniora Słoneczny',c:'Poznań',r:'wielkopolskie',lat:52.405,lng:16.86,d:7,p:4500,s:4.6,o:38,a:'dostępne',care:['Dzienna'],x:['Rehabilitacja','Diety','Ogród'],color:'#e5ba73'},
{id:6,n:'Dom Opieki Leśne Zacisze',c:'Białystok',r:'podlaskie',lat:53.15,lng:23.19,d:32,p:5900,s:4.8,o:52,a:'brak miejsc',care:['Całodobowa','Medyczna'],x:['Diety','Ogród'],color:'#9eb99c'},
{id:7,n:'Rezydencja Spokojny Port',c:'Szczecin',r:'zachodniopomorskie',lat:53.44,lng:14.49,d:14,p:7600,s:4.7,o:44,a:'2 miejsca',care:['Całodobowa','Paliatywna'],x:['Pokój 1-os.','Diety'],color:'#b7afc9'},
{id:8,n:'Dzienny Dom Blisko',c:'Lublin',r:'lubelskie',lat:51.235,lng:22.59,d:11,p:4200,s:4.8,o:29,a:'dostępne',care:['Dzienna','Medyczna'],x:['Rehabilitacja','Diety','Ogród'],color:'#c4cfa9'},
{id:9,n:'Senior Residence Parkowa',c:'Łódź',r:'łódzkie',lat:51.76,lng:19.43,d:16,p:6100,s:4.7,o:35,a:'2 miejsca',care:['Całodobowa','Medyczna'],x:['Rehabilitacja','Diety'],color:'#c9b5a1'},
{id:10,n:'Dom Spokojna Dolina',c:'Katowice',r:'śląskie',lat:50.25,lng:19.04,d:10,p:6700,s:4.8,o:41,a:'1 miejsce',care:['Całodobowa','Paliatywna'],x:['Pokój 1-os.','Ogród'],color:'#aabda8'},
{id:11,n:'Ośrodek Seniora Nad Brdą',c:'Bydgoszcz',r:'kujawsko-pomorskie',lat:53.13,lng:18.01,d:8,p:5700,s:4.6,o:26,a:'dostępne',care:['Dzienna','Medyczna'],x:['Rehabilitacja','Diety'],color:'#adc5ca'},
{id:12,n:'Rezydencja Warmińska',c:'Olsztyn',r:'warmińsko-mazurskie',lat:53.79,lng:20.48,d:13,p:6500,s:4.7,o:31,a:'2 miejsca',care:['Całodobowa'],x:['Diety','Ogród','Pokój 1-os.'],color:'#a6ba9b'},
{id:13,n:'Dom Seniora Podkarpacie',c:'Rzeszów',r:'podkarpackie',lat:50.04,lng:22.02,d:9,p:5800,s:4.8,o:39,a:'1 miejsce',care:['Całodobowa','Medyczna'],x:['Rehabilitacja','Ogród'],color:'#cbb89d'},
{id:14,n:'Opolski Dom Opieki',c:'Opole',r:'opolskie',lat:50.67,lng:17.92,d:7,p:6200,s:4.6,o:22,a:'dostępne',care:['Całodobowa','Dzienna'],x:['Diety','Pokój 1-os.'],color:'#b5b2c6'},
{id:15,n:'Przystań Świętokrzyska',c:'Kielce',r:'świętokrzyskie',lat:50.87,lng:20.63,d:11,p:5600,s:4.7,o:28,a:'2 miejsca',care:['Całodobowa','Medyczna'],x:['Rehabilitacja','Ogród'],color:'#c0cba8'},
{id:16,n:'Zielonogórski Klub Seniora',c:'Zielona Góra',r:'lubuskie',lat:51.94,lng:15.50,d:6,p:4300,s:4.7,o:25,a:'dostępne',care:['Dzienna'],x:['Rehabilitacja','Diety','Ogród'],color:'#a3bf9c'}];
const extraFeatures={1:['Łazienka dostępna','Winda','Bez barier','System przywoławczy','Demencja','Dieta cukrzycowa'],2:['Łazienka dostępna','Winda','Alzheimer','Dieta lekkostrawna','Kaplica'],3:['Bez barier','Winda','System przywoławczy','Parkinson','Fizjoterapia'],4:['Łazienka dostępna','Bez barier','Tlenoterapia','Demencja','Dieta bezglutenowa'],5:['Bez barier','Transport','Zajęcia terapeutyczne'],6:['Winda','System przywoławczy','Dieta cukrzycowa','Alzheimer'],7:['Łazienka dostępna','Winda','Opieka hospicyjna','Kaplica'],8:['Bez barier','Transport','Fizjoterapia','Dieta lekkostrawna'],9:['Łazienka dostępna','System przywoławczy','Demencja','Dieta cukrzycowa'],10:['Winda','Bez barier','Opieka hospicyjna','Alzheimer'],11:['Łazienka dostępna','Transport','Fizjoterapia'],12:['Winda','System przywoławczy','Demencja','Kaplica'],13:['Bez barier','Łazienka dostępna','Parkinson','Dieta lekkostrawna'],14:['Winda','System przywoławczy','Dieta bezglutenowa'],15:['Bez barier','Łazienka dostępna','Demencja','Fizjoterapia'],16:['Bez barier','Transport','Zajęcia terapeutyczne']};data.forEach(f=>f.x.push(...(extraFeatures[f.id]||[])))
const cityCoords={'Warszawa':[52.23,21.01],'Kraków':[50.06,19.94],'Wrocław':[51.11,17.03],'Łódź':[51.76,19.46],'Poznań':[52.41,16.93],'Gdańsk':[54.35,18.65],'Szczecin':[53.43,14.55],'Bydgoszcz':[53.12,18.01],'Lublin':[51.25,22.57],'Białystok':[53.13,23.16],'Katowice':[50.26,19.02],'Rzeszów':[50.04,22.00],'Olsztyn':[53.78,20.48],'Opole':[50.68,17.92],'Kielce':[50.87,20.63],'Zielona Góra':[51.94,15.51]};function syncCustomFacility(){let c=null;try{c=JSON.parse(localStorage.getItem('blisko_facility_1')||'null')}catch{}if(!c)return;let f=data[0],coords=cityCoords[c.city];f.n=c.name||f.n;f.c=c.city||f.c;f.r=c.region||f.r;f.d=c.distance??f.d;f.p=c.doublePrice||c.singlePrice||f.p;if(coords)[f.lat,f.lng]=coords;let services=c.services||[],careMap={'Opieka całodobowa':'Całodobowa','Opieka medyczna':'Medyczna','Opieka paliatywna':'Paliatywna','Pobyt dzienny':'Dzienna'};f.care=services.filter(x=>careMap[x]).map(x=>careMap[x]);f.x=services.filter(x=>!careMap[x]).map(x=>x.replace('Diety specjalistyczne','Diety').replace('Ogród terapeutyczny','Ogród'));if(c.singlePrice)f.x.push('Pokój 1-os.');let active=Object.values(c.vacancies||{}).filter(v=>v.active),available=active.filter(v=>['now','30days','1-3months'].includes(v.status)).reduce((sum,v)=>sum+(v.count||0),0);f.a=available?`${available} ${available===1?'miejsce':'miejsca'}`:active.some(v=>v.status==='waitlist')?'lista oczekujących':'brak miejsc'}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let fav=new Set(),quick='',map,layer;const money=n=>new Intl.NumberFormat('pl-PL').format(n)+' zł';
function get(){let term=$('#where').value.toLowerCase(),checks=$$('#filters input:checked').filter(x=>!x.id).map(x=>x.value),care=$('#care').value,max=+$('#price').value;let a=data.filter(f=>(!term||(f.c+' '+f.r).toLowerCase().includes(term))&&(!care||f.care.includes(care))&&(!quick||[...f.care,...f.x].includes(quick))&&f.p<=max&&checks.every(v=>[...f.care,...f.x].includes(v))&&(!$('#available').checked||f.a!=='brak miejsc'));let sort=$('#sort').value;return a.sort((a,b)=>sort==='distance'?a.d-b.d:sort==='price'?a.p-b.p:sort==='rating'?b.s-a.s:b.s-a.s)}
function loadMapBackup(){return new Promise(resolve=>{if(window.L)return resolve();let css=document.createElement('link');css.rel='stylesheet';css.href='https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.css';document.head.appendChild(css);let script=document.createElement('script');script.src='https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.js';script.onload=resolve;script.onerror=resolve;document.head.appendChild(script)})}
async function initMap(){if(!window.L)await loadMapBackup();if(!window.L){$('#realMap').innerHTML='<div class="map-error"><b>Mapa chwilowo niedostępna</b><span>Lista placówek nadal działa. Odśwież stronę, aby ponowić ładowanie mapy.</span></div>';return}map=L.map('realMap',{zoomControl:true,scrollWheelZoom:false}).setView([52.1,19.4],6);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);layer=L.layerGroup().addTo(map);setTimeout(()=>map.invalidateSize(),100)}
function renderMap(items,fit=false){if(!map)return;layer.clearLayers();items.forEach(f=>{let icon=L.divIcon({className:'facility-dot',html:'',iconSize:[18,18]});L.marker([f.lat,f.lng],{icon}).addTo(layer).bindPopup(`<b>${f.n}</b><span>${f.c} • od ${money(f.p)}/mies.</span><a href="detail.html?id=${f.id}">Zobacz placówkę →</a>`)});$('#mapCount').textContent=`${items.length} ${items.length===1?'placówka':'placówek'}`;if(fit&&items.length){let bounds=L.latLngBounds(items.map(f=>[f.lat,f.lng]));map.fitBounds(bounds,{padding:[35,35],maxZoom:11})}else if(fit){map.setView([52.1,19.4],6)}}
function render(fit=false){let a=get();$('#count').textContent=a.length+' wyników';$('#summary').textContent=`Znaleziono ${a.length} placówek w Polsce`;$('#empty').hidden=!!a.length;$('#cards').innerHTML=a.map(f=>`<article class="card"><div class="photo" style="--c:${f.color}"><i>⌂</i><span>${f.a}</span><button data-fav="${f.id}">${fav.has(f.id)?'♥':'♡'}</button></div><div class="info"><small>★ ${f.s} (${f.o} opinii)</small><h3>${f.n}</h3><p>⌖ ${f.c}, ${f.r} • ${f.d} km</p><div class="tags">${[...f.care,...f.x].slice(0,4).map(x=>`<b>${x}</b>`).join('')}</div><footer><span>od <strong>${money(f.p)}</strong>/ miesiąc</span><button data-detail="${f.id}">Zobacz →</button></footer></div></article>`).join('');$$('[data-fav]').forEach(b=>b.onclick=()=>{let id=+b.dataset.fav;fav.has(id)?fav.delete(id):fav.add(id);$('#saved span').textContent=fav.size;toast(fav.has(id)?'Dodano do zapisanych':'Usunięto z zapisanych');render()});$$('[data-detail]').forEach(b=>b.onclick=()=>location.href=`detail.html?id=${b.dataset.detail}`);renderMap(a,fit)}
function toast(t){$('#toast').textContent=t;$('#toast').className='show';clearTimeout(window.tt);window.tt=setTimeout(()=>$('#toast').className='',2000)}
function clear(){quick='';$('#where').value='';$('#care').value='';$$('#filters input').forEach(x=>x.checked=false);$('#price').value=10000;$('#priceText').textContent='10 000 zł';$$('.chips button').forEach(x=>x.className='');render(true)}
function initAiAssistant(){
 const trigger=document.createElement('button');trigger.type='button';trigger.className='aiTrigger';trigger.innerHTML='<span>✦</span><b>Pomóż mi wybrać placówkę</b><small>Opisz potrzeby bliskiej osoby — asystent znajdzie najlepiej dopasowane miejsca</small>';
 $('.hero form').insertAdjacentElement('afterend',trigger);
 document.body.insertAdjacentHTML('beforeend',`<div class="aiModal" id="aiModal" hidden><section class="aiDialog"><header><div><small>ASYSTENT BLISKO</small><h2>Znajdźmy odpowiednie miejsce</h2><p>Odpowiedz na kilka pytań. Nie podawaj nazwiska, PESEL-u ani dokumentacji medycznej.</p></div><button type="button" id="aiClose" aria-label="Zamknij">×</button></header><form id="aiForm"><div class="aiGrid"><label>Gdzie ma znajdować się placówka?<select name="location"><option value="">Cała Polska</option>${[...new Set(data.map(f=>f.c))].map(c=>`<option>${c}</option>`).join('')}</select></label><label>Maksymalny budżet miesięczny<select name="budget"><option value="10000">do 10 000 zł</option><option value="8000">do 8 000 zł</option><option value="6500">do 6 500 zł</option><option value="5000">do 5 000 zł</option></select></label><label>Potrzebny rodzaj opieki<select name="care"><option value="Całodobowa">Opieka całodobowa</option><option value="Medyczna">Opieka medyczna</option><option value="Paliatywna">Opieka paliatywna</option><option value="Dzienna">Pobyt dzienny</option></select></label><label>Samodzielność ruchowa<select name="mobility"><option value="">Osoba samodzielna</option><option value="barriers">Potrzebuje miejsca bez barier</option><option value="bathroom">Potrzebuje dostosowanej łazienki</option></select></label><label>Szczególne potrzeby<select name="condition"><option value="">Brak / jeszcze nie wiem</option><option>Demencja</option><option>Alzheimer</option><option>Parkinson</option><option>Opieka hospicyjna</option><option>Tlenoterapia</option></select></label><label>Preferowany pokój<select name="room"><option value="">Bez znaczenia</option><option value="Pokój 1-os.">Pokój jednoosobowy</option></select></label><label class="wide">Co jeszcze jest ważne?<textarea name="description" rows="3" placeholder="Np. spokojna okolica, ogród, rehabilitacja, dieta cukrzycowa, blisko rodziny…"></textarea></label></div><label class="aiConsent"><input type="checkbox" required> Rozumiem, że to wstępne dopasowanie, a możliwość przyjęcia i zakres opieki potwierdza placówka.</label><button class="aiSubmit">Znajdź dopasowane placówki →</button></form><div id="aiResults" hidden></div></section></div>`);
 const modal=$('#aiModal'),form=$('#aiForm'),results=$('#aiResults');trigger.onclick=()=>{modal.hidden=false;document.body.classList.add('aiLocked')};$('#aiClose').onclick=()=>{modal.hidden=true;document.body.classList.remove('aiLocked')};modal.onclick=e=>{if(e.target===modal)$('#aiClose').click()};
 form.onsubmit=e=>{e.preventDefault();let v=Object.fromEntries(new FormData(form)),words=v.description.toLowerCase(),wanted=[];if(v.mobility==='barriers')wanted.push('Bez barier');if(v.mobility==='bathroom')wanted.push('Łazienka dostępna');if(v.condition)wanted.push(v.condition);[['ogród','Ogród'],['rehabil','Rehabilitacja'],['cukrzyc','Dieta cukrzycowa'],['bezgluten','Dieta bezglutenowa'],['wind','Winda'],['transport','Transport']].forEach(([word,feature])=>{if(words.includes(word))wanted.push(feature)});if(v.room)wanted.push(v.room);let ranked=data.map(f=>{let score=0,reasons=[],missing=[];if(!v.location||f.c===v.location){score+=v.location?30:5;if(v.location)reasons.push(`lokalizacja: ${f.c}`)}else score-=15;if(f.p<=+v.budget){score+=20;reasons.push(`cena od ${money(f.p)}`)}else{score-=20;missing.push('powyżej budżetu')}if(f.care.includes(v.care)){score+=25;reasons.push(v.care.toLowerCase())}else missing.push(`brak oznaczenia: ${v.care.toLowerCase()}`);wanted.forEach(x=>{if(f.x.includes(x)){score+=10;reasons.push(x.toLowerCase())}else missing.push(x.toLowerCase())});if(f.a!=='brak miejsc'){score+=10;reasons.push(f.a)}else missing.push('brak miejsc obecnie');score+=f.s;return{f,score,reasons:[...new Set(reasons)],missing:[...new Set(missing)]}}).sort((a,b)=>b.score-a.score).slice(0,3);results.hidden=false;form.hidden=true;results.innerHTML=`<div class="aiResultHead"><small>NAJLEPSZE DOPASOWANIA</small><h2>Te miejsca warto sprawdzić</h2><p>Ranking powstał na podstawie podanych preferencji i danych dostępnych w Blisko.</p></div><div class="aiMatches">${ranked.map((m,i)=>`<article><span class="aiRank">${i+1}</span><div><small>★ ${m.f.s} · ${m.f.c}</small><h3>${m.f.n}</h3><p><b>Dlaczego pasuje:</b> ${m.reasons.slice(0,4).join(', ')||'zbliżony profil potrzeb'}.</p>${m.missing.length?`<p class="aiCaution"><b>Do potwierdzenia:</b> ${m.missing.slice(0,3).join(', ')}.</p>`:''}<button data-detail="${m.f.id}">Zobacz placówkę →</button></div></article>`).join('')}</div><button class="aiAgain" type="button">Zmień odpowiedzi</button>`;results.querySelector('.aiAgain').onclick=()=>{results.hidden=true;form.hidden=false}};
}
function initAiAssistantV2(){
 const trigger=document.createElement('button');trigger.type='button';trigger.className='aiTrigger';trigger.innerHTML='<span>✦</span><b>Opowiedz, jakiego miejsca potrzebujecie</b><small>Asystent zrozumie opis i dopasuje placówki bez wypełniania filtrów</small>';$('.hero form').insertAdjacentElement('afterend',trigger);
 document.body.insertAdjacentHTML('beforeend',`<div class="aiModal" id="aiModal" hidden><section class="aiDialog aiConversation"><header><div><small>ASYSTENT BLISKO</small><h2>Opisz sytuację własnymi słowami</h2><p>Możesz podać miejscowość, promień, budżet, stan zdrowia i ważne udogodnienia.</p></div><button type="button" id="aiClose" aria-label="Zamknij">×</button></header><div class="aiChat"><div class="aiBubble"><b>W czym mogę pomóc?</b><p>Przykład: „Szukam opieki całodobowej w promieniu 50 km od Nadarzyna dla mamy z demencją. Ważna jest łazienka bez barier, ogród i budżet do 8000 zł.”</p></div><form id="aiForm"><label for="aiDescription">Opisz potrzeby bliskiej osoby</label><textarea id="aiDescription" name="description" rows="6" required placeholder="Napisz tutaj, czego szukacie…"></textarea><small>Nie wpisuj nazwiska, PESEL-u ani danych z dokumentacji medycznej.</small><label class="aiConsent"><input type="checkbox" required> Rozumiem, że dopasowanie jest wstępne, a zakres opieki potwierdza placówka.</label><button class="aiSubmit">Dopasuj placówki →</button></form><div id="aiResults" hidden></div></div></section></div>`);
 const modal=$('#aiModal'),form=$('#aiForm'),results=$('#aiResults');trigger.onclick=()=>{modal.hidden=false;document.body.classList.add('aiLocked')};$('#aiClose').onclick=()=>{modal.hidden=true;document.body.classList.remove('aiLocked')};modal.onclick=e=>{if(e.target===modal)$('#aiClose').click()};
 const locations={nadarzyn:[52.094,20.807],warszawa:[52.23,21.01],kraków:[50.06,19.94],krakow:[50.06,19.94],wrocław:[51.11,17.03],wroclaw:[51.11,17.03],łódź:[51.76,19.46],lodz:[51.76,19.46],poznań:[52.41,16.93],poznan:[52.41,16.93],gdańsk:[54.35,18.65],gdansk:[54.35,18.65],szczecin:[53.43,14.55],bydgoszcz:[53.12,18.01],lublin:[51.25,22.57],białystok:[53.13,23.16],bialystok:[53.13,23.16],katowice:[50.26,19.02],rzeszów:[50.04,22],rzeszow:[50.04,22],olsztyn:[53.78,20.48],opole:[50.68,17.92],kielce:[50.87,20.63],'zielona góra':[51.94,15.51],'zielona gora':[51.94,15.51]};
 const distance=(a,b)=>{let rad=x=>x*Math.PI/180,dLat=rad(b[0]-a[0]),dLng=rad(b[1]-a[1]),q=Math.sin(dLat/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))};
 form.onsubmit=e=>{e.preventDefault();let text=$('#aiDescription').value.trim(),lower=text.toLowerCase(),radius=+(lower.match(/(?:promieniu|promień|promien|do)\s*(\d+)\s*km/)?.[1]||lower.match(/(\d+)\s*km/)?.[1]||0),place=Object.keys(locations).sort((a,b)=>b.length-a.length).find(x=>lower.includes(x)),provinceAliases=[['dolnośląsk','dolnośląskie'],['kujawsko-pomorsk','kujawsko-pomorskie'],['lubelsk','lubelskie'],['lubusk','lubuskie'],['łódzk','łódzkie'],['małopolsk','małopolskie'],['mazowieck','mazowieckie'],['opolsk','opolskie'],['podkarpack','podkarpackie'],['podlask','podlaskie'],['pomorsk','pomorskie'],['śląsk','śląskie'],['świętokrzysk','świętokrzyskie'],['warmińsko-mazursk','warmińsko-mazurskie'],['wielkopolsk','wielkopolskie'],['zachodniopomorsk','zachodniopomorskie']],province=provinceAliases.find(([stem])=>lower.includes(stem))?.[1];
  if(radius&&!place){results.hidden=false;results.innerHTML='<div class="aiNeedMore"><h3>Nie rozpoznaję miejscowości</h3><p>Nie chcę pokazywać przypadkowych placówek. Podaj proszę nazwę najbliższego większego miasta albo województwo.</p><button class="aiAgain" type="button">Uzupełnij opis</button></div>';results.querySelector('button').onclick=()=>{$('#aiDescription').focus()};return}
  let budget=+(lower.match(/(?:budżet|budzet|do|max(?:ymalnie)?)\D{0,12}(\d[\d\s]*)\s*(?:zł|zl)/)?.[1]||'10000').replace(/\s/g,''),care=lower.includes('paliatyw')?'Paliatywna':lower.includes('dzienn')?'Dzienna':lower.includes('medycz')?'Medyczna':'Całodobowa',wanted=[];[['demenc','Demencja'],['alzheimer','Alzheimer'],['parkinson','Parkinson'],['hospic','Opieka hospicyjna'],['tlen','Tlenoterapia'],['bez barier','Bez barier'],['łazien','Łazienka dostępna'],['lazien','Łazienka dostępna'],['wind','Winda'],['ogród','Ogród'],['ogrod','Ogród'],['rehabil','Rehabilitacja'],['cukrzyc','Dieta cukrzycowa'],['bezgluten','Dieta bezglutenowa'],['transport','Transport'],['jednoosob','Pokój 1-os.']].forEach(([word,val])=>{if(lower.includes(word))wanted.push(val)});
  let origin=place&&locations[place],pool=data.map(f=>({f,km:origin?Math.round(distance(origin,[f.lat,f.lng])):null})).filter(x=>(!origin||!radius||x.km<=radius)&&(!province||x.f.r===province));if(!pool.length){results.hidden=false;results.innerHTML=`<div class="aiNeedMore"><h3>Nie znaleźliśmy miejsca w zadanym obszarze</h3><p>${origin&&radius?`W bazie Blisko nie ma obecnie placówki w promieniu ${radius} km od wskazanej miejscowości.`:'Nie mamy obecnie placówki spełniającej ten warunek lokalizacji.'} Nie rozszerzyliśmy obszaru automatycznie.</p><button class="aiAgain" type="button">Zmień opis</button></div>`;results.querySelector('button').onclick=()=>{$('#aiDescription').focus()};return}
  let ranked=pool.map(({f,km})=>{let score=0,reasons=[],missing=[];if(km!==null){score+=Math.max(0,35-km/3);reasons.push(`${km} km od ${place}`)}else if(province){score+=25;reasons.push(`woj. ${province}`)}if(f.p<=budget){score+=20;reasons.push(`cena od ${money(f.p)}`)}else{score-=25;missing.push('cena przekracza budżet')}if(f.care.includes(care)){score+=25;reasons.push(care.toLowerCase())}else missing.push(`zakres: ${care.toLowerCase()}`);wanted.forEach(x=>{if(f.x.includes(x)){score+=10;reasons.push(x.toLowerCase())}else missing.push(x.toLowerCase())});if(f.a!=='brak miejsc'){score+=10;reasons.push(f.a)}else missing.push('brak miejsc obecnie');return{f,score,reasons,missing,km}}).sort((a,b)=>b.score-a.score).slice(0,3);
  form.hidden=true;results.hidden=false;results.innerHTML=`<div class="aiResultHead"><small>DOPASOWANIE DO OPISU</small><h2>${ranked.length===1?'Znaleźliśmy jedno miejsce':'Te miejsca warto sprawdzić'}</h2><p>${origin&&radius?`Pokazujemy wyłącznie placówki do ${radius} km od ${place}.`:province?`Pokazujemy wyłącznie województwo ${province}.`:'Ranking uwzględnia potrzeby opisane przez rodzinę.'}</p></div><div class="aiMatches">${ranked.map((m,i)=>`<article><span class="aiRank">${i+1}</span><div><small>★ ${m.f.s} · ${m.f.c}${m.km!==null?` · ${m.km} km`:''}</small><h3>${m.f.n}</h3><p><b>Dlaczego pasuje:</b> ${m.reasons.slice(0,5).join(', ')}.</p>${m.missing.length?`<p class="aiCaution"><b>Do potwierdzenia:</b> ${m.missing.slice(0,3).join(', ')}.</p>`:''}<button data-detail="${m.f.id}">Zobacz placówkę →</button></div></article>`).join('')}</div><button class="aiAgain" type="button">Zmień opis</button>`;results.querySelector('.aiAgain').onclick=()=>{results.hidden=true;form.hidden=false;$('#aiDescription').focus()}};
}
document.addEventListener('click',e=>{let button=e.target.closest('[data-detail]'),card=e.target.closest('.card');if(e.target.closest('[data-fav]'))return;let id=button?.dataset.detail||card?.querySelector('[data-detail]')?.dataset.detail;if(!id)return;e.preventDefault();e.stopImmediatePropagation();let url=`detail.html?id=${id}`;matchMedia('(min-width: 851px)').matches?window.open(url,'_blank','noopener'):location.href=url},true);
const filterGroups=[['Dostępność budynku',['Łazienka dostępna','Bez barier','Winda','System przywoławczy']],['Potrzeby zdrowotne',['Demencja','Alzheimer','Parkinson','Opieka hospicyjna','Tlenoterapia']],['Wyżywienie',['Dieta cukrzycowa','Dieta lekkostrawna','Dieta bezglutenowa']],['Dodatkowe udogodnienia',['Fizjoterapia','Transport','Zajęcia terapeutyczne','Kaplica']]];let filterAnchor=$('#filters fieldset:last-of-type');filterAnchor.insertAdjacentHTML('beforebegin',filterGroups.map(([title,items])=>`<fieldset class="extendedFilter"><legend>${title}</legend>${items.map(item=>`<label><input type="checkbox" value="${item}"> ${item}</label>`).join('')}</fieldset>`).join(''));
initAiAssistantV2();
$('#search').onsubmit=e=>{e.preventDefault();render(true);$('#wyniki').scrollIntoView({behavior:'smooth'})};$('#where').onchange=()=>render(true);$$('#filters input').forEach(x=>x.onchange=()=>render());$('#price').oninput=e=>{$('#priceText').textContent=money(+e.target.value);render()};$('#sort').onchange=()=>render();$('#clear').onclick=clear;$$('.chips button').forEach(b=>b.onclick=()=>{quick=quick===b.dataset.q?'':b.dataset.q;$$('.chips button').forEach(x=>x.classList.toggle('active',x.dataset.q===quick));render()});$$('[data-plan]').forEach(b=>b.onclick=()=>toast(`Wybrano plan ${b.dataset.plan} — formularz rejestracji dodamy w panelu placówki`));$('#filterToggle').onclick=()=>$('#filters').classList.toggle('open');syncCustomFacility();window.addEventListener('storage',e=>{if(e.key==='blisko_facility_1'){syncCustomFacility();render(true);toast('Zaktualizowano dane placówki')}});window.addEventListener('pageshow',()=>{syncCustomFacility();render()});initMap().then(()=>render());

