const data=[
{id:1,n:'Dom Seniora Zielona Przystań',c:'Warszawa',r:'mazowieckie',d:12,p:7200,s:4.9,o:84,a:'2 miejsca',care:['Całodobowa','Medyczna'],x:['Rehabilitacja','Diety','Pokój 1-os.','Ogród'],pos:[63,42],color:'#bdcfaa'},
{id:2,n:'Rezydencja Pod Lipami',c:'Kraków',r:'małopolskie',d:18,p:6800,s:4.8,o:61,a:'1 miejsce',care:['Całodobowa','Paliatywna'],x:['Diety','Pokój 1-os.','Ogród'],pos:[55,79],color:'#dfb49f'},
{id:3,n:'Przystań Dobra Jesień',c:'Gdańsk',r:'pomorskie',d:9,p:8100,s:4.9,o:47,a:'od 15.09',care:['Całodobowa','Medyczna'],x:['Rehabilitacja','Diety','Ogród'],pos:[52,18],color:'#a9c9d2'},
{id:4,n:'Centrum Opieki Harmonia',c:'Wrocław',r:'dolnośląskie',d:25,p:6400,s:4.7,o:93,a:'3 miejsca',care:['Całodobowa','Medyczna','Paliatywna'],x:['Rehabilitacja','Pokój 1-os.'],pos:[29,66],color:'#d7c69f'},
{id:5,n:'Klub Seniora Słoneczny',c:'Poznań',r:'wielkopolskie',d:7,p:4500,s:4.6,o:38,a:'dostępne',care:['Dzienna'],x:['Rehabilitacja','Diety','Ogród'],pos:[30,45],color:'#e5ba73'},
{id:6,n:'Dom Opieki Leśne Zacisze',c:'Białystok',r:'podlaskie',d:32,p:5900,s:4.8,o:52,a:'brak miejsc',care:['Całodobowa','Medyczna'],x:['Diety','Ogród'],pos:[82,35],color:'#9eb99c'},
{id:7,n:'Rezydencja Spokojny Port',c:'Szczecin',r:'zachodniopomorskie',d:14,p:7600,s:4.7,o:44,a:'2 miejsca',care:['Całodobowa','Paliatywna'],x:['Pokój 1-os.','Diety'],pos:[11,35],color:'#b7afc9'},
{id:8,n:'Dzienny Dom Blisko',c:'Lublin',r:'lubelskie',d:11,p:4200,s:4.8,o:29,a:'dostępne',care:['Dzienna','Medyczna'],x:['Rehabilitacja','Diety','Ogród'],pos:[76,64],color:'#c4cfa9'}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let fav=new Set(),quick='';const money=n=>new Intl.NumberFormat('pl-PL').format(n)+' zł';
function get(){let term=$('#where').value.toLowerCase(),checks=$$('#filters input:checked').filter(x=>!x.id).map(x=>x.value),care=$('#care').value,max=+$('#price').value;let a=data.filter(f=>(!term||(f.c+' '+f.r).toLowerCase().includes(term))&&(!care||f.care.includes(care))&&(!quick||[...f.care,...f.x].includes(quick))&&f.p<=max&&checks.every(v=>[...f.care,...f.x].includes(v))&&(!$('#available').checked||f.a!=='brak miejsc'));let sort=$('#sort').value;return a.sort((a,b)=>sort==='distance'?a.d-b.d:sort==='price'?a.p-b.p:sort==='rating'?b.s-a.s:b.s-a.s)}
function render(){let a=get();$('#count').textContent=a.length+' wyników';$('#summary').textContent=`Znaleziono ${a.length} placówek w Polsce`;$('#empty').hidden=!!a.length;$('#cards').innerHTML=a.map(f=>`<article class="card"><div class="photo" style="--c:${f.color}"><i>⌂</i><span>${f.a}</span><button data-fav="${f.id}">${fav.has(f.id)?'♥':'♡'}</button></div><div class="info"><small>★ ${f.s} (${f.o} opinii)</small><h3>${f.n}</h3><p>⌖ ${f.c}, ${f.r} • ${f.d} km</p><div class="tags">${[...f.care,...f.x].slice(0,4).map(x=>`<b>${x}</b>`).join('')}</div><footer><span>od <strong>${money(f.p)}</strong>/ miesiąc</span><button data-detail>Zobacz →</button></footer></div></article>`).join('');$('#markers').innerHTML=a.map(f=>`<button style="left:${f.pos[0]}%;top:${f.pos[1]}%" title="${f.n}">${money(f.p).replace(' zł','')}</button>`).join('');$$('[data-fav]').forEach(b=>b.onclick=()=>{let id=+b.dataset.fav;fav.has(id)?fav.delete(id):fav.add(id);$('#saved span').textContent=fav.size;toast(fav.has(id)?'Dodano do zapisanych':'Usunięto z zapisanych');render()});$$('[data-detail]').forEach(b=>b.onclick=()=>toast('Profil placówki będzie następnym widokiem'))}
function toast(t){$('#toast').textContent=t;$('#toast').className='show';clearTimeout(window.tt);window.tt=setTimeout(()=>$('#toast').className='',2000)}
function clear(){quick='';$('#where').value='';$('#care').value='';$$('#filters input').forEach(x=>x.checked=false);$('#price').value=10000;$('#priceText').textContent='10 000 zł';$$('.chips button').forEach(x=>x.className='');render()}
$('#search').onsubmit=e=>{e.preventDefault();render();$('#wyniki').scrollIntoView({behavior:'smooth'})};$$('#filters input').forEach(x=>x.onchange=render);$('#price').oninput=e=>{$('#priceText').textContent=money(+e.target.value);render()};$('#sort').onchange=render;$('#clear').onclick=clear;$$('.chips button').forEach(b=>b.onclick=()=>{quick=quick===b.dataset.q?'':b.dataset.q;$$('.chips button').forEach(x=>x.classList.toggle('active',x.dataset.q===quick));render()});$('#filterToggle').onclick=()=>$('#filters').classList.toggle('open');$('#date').min=new Date().toISOString().slice(0,10);render();
