const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const seed=[{name:'Anna',email:'rodzina@blisko.pl',password:'demo123',role:'family'},{name:'Marek',facility:'Dom Seniora Basic',email:'basic@blisko.pl',password:'demo123',role:'provider',plan:'free',kyc:'verified'},{name:'Anna',facility:'Zielona Przystań',email:'partner@blisko.pl',password:'demo123',role:'provider',plan:'partner',kyc:'verified'},{name:'Piotr',facility:'Rezydencje Blisko',email:'pro@blisko.pl',password:'demo123',role:'provider',plan:'pro',kyc:'verified'}];
let role='family',mode='login';function accounts(){try{return[...seed,...JSON.parse(localStorage.getItem('blisko_accounts')||'[]')]}catch{return seed}}function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(window.at);window.at=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
$('.demoAccounts').innerHTML='<b>Konta demonstracyjne</b><button data-demo="family">Rodzina · pełny kontakt z placówkami</button><button data-demo="basic">Placówka Basic · profil podstawowy</button><button data-demo="partner">Placówka Partner · zapytania i analityka</button><button data-demo="pro">Placówka Pro · pełna analityka</button><small>Hasło do wszystkich kont: demo123</small>';
$('#authForm').insertAdjacentHTML('beforeend',`<section class="kycFields" hidden><div class="kycIntro"><b>Weryfikacja uprawnienia placówki</b><p>Sprawdzimy placówkę we właściwym publicznym rejestrze. REGON nie jest dowodem zezwolenia na prowadzenie opieki.</p></div><div class="kycGrid"><label class="wide">Rodzaj placówki<select name="facilityType"><option>Placówka całodobowej opieki — rejestr wojewody</option><option>Dom pomocy społecznej (DPS)</option><option>ZOL / ZPO — rejestr podmiotów leczniczych</option><option>Placówka dziennego pobytu</option></select></label><label>NIP podmiotu prowadzącego<input name="nip" inputmode="numeric" placeholder="0000000000"></label><label>Numer placówki we właściwym rejestrze<input name="registryNumber" placeholder="np. PS-III.9420…"></label><label class="wide">Numer i data decyzji / zezwolenia<input name="license" placeholder="np. WPS-III.9423… z dnia …"></label><label class="wide">Adres placówki<input name="address" placeholder="Ulica, kod pocztowy, miejscowość"></label><label>Osoba kierująca placówką<input name="manager" placeholder="Imię i nazwisko"></label><label>Osoba zakładająca konto<input name="representative" placeholder="Imię i nazwisko"></label></div><label class="kycConfirm"><input name="kycConfirm" type="checkbox"> Potwierdzam uprawnienie do reprezentowania placówki i zgodność danych.</label><div class="kycSteps"><span><b>1</b>Dane konta</span><span><b>2</b>Rejestr i decyzja</span><span><b>3</b>Aktywacja profilu</span></div></section>`);
function paint(){$$('.roleTabs button').forEach(b=>b.classList.toggle('active',b.dataset.role===role));$$('.modeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$$('.registerOnly').forEach(x=>x.hidden=mode!=='register');$$('.providerOnly').forEach(x=>x.hidden=role!=='provider');$('.kycFields').hidden=!(mode==='register'&&role==='provider');$('.submit').textContent=mode==='login'?'Zaloguj się →':role==='provider'?'Wyślij placówkę do weryfikacji →':'Utwórz konto →'}
$$('[data-role]').forEach(b=>b.onclick=()=>{role=b.dataset.role;paint()});$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;paint()});$$('[data-demo]').forEach(b=>b.onclick=()=>{let type=b.dataset.demo;role=type==='family'?'family':'provider';mode='login';paint();$('[name=email]').value={family:'rodzina@blisko.pl',basic:'basic@blisko.pl',partner:'partner@blisko.pl',pro:'pro@blisko.pl'}[type];$('[name=password]').value='demo123'});$('#forgot').onclick=()=>toast('W wersji demonstracyjnej użyj jednego z kont demo.');
function login(account){let session={...account};delete session.password;localStorage.setItem('blisko_session',JSON.stringify(session));if(account.role==='provider')localStorage.setItem('blisko_plan',account.plan||'free');setTimeout(()=>location.href=account.role==='provider'?'dashboard.html':'index.html',450)}
$('#authForm').onsubmit=e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.currentTarget));if(mode==='register'){if(accounts().some(a=>a.email.toLowerCase()===v.email.toLowerCase()))return toast('Konto z tym adresem już istnieje');if(role==='provider'&&(!v.nip||!v.address||!v.representative||!v.kycConfirm))return toast('Uzupełnij wymagane dane KYC');let account={name:v.name||'Użytkownik',facility:v.facility||'',email:v.email.toLowerCase(),password:v.password,role,plan:role==='provider'?'free':undefined,kyc:role==='provider'?'pending':undefined,nip:v.nip||'',address:v.address||''};let saved=[];try{saved=JSON.parse(localStorage.getItem('blisko_accounts')||'[]')}catch{}saved.push(account);localStorage.setItem('blisko_accounts',JSON.stringify(saved));login(account);toast(role==='provider'?'Konto utworzone — KYC oczekuje':'Konto utworzone')}else{let account=accounts().find(a=>a.email.toLowerCase()===v.email.toLowerCase()&&a.password===v.password&&a.role===role);if(!account)return toast('Nieprawidłowy e-mail, hasło lub typ konta');login(account);toast(`Zalogowano${account.plan?' · '+({free:'Basic',partner:'Partner',pro:'Pro'}[account.plan]):''}`)}};paint();

