const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let view=new Date(),selected='',slide=0;const months=['styczeń','luty','marzec','kwiecień','maj','czerwiec','lipiec','sierpień','wrzesień','październik','listopad','grudzień'],photos=['Salon i wspólna przestrzeń','Ogród terapeutyczny','Pokój jednoosobowy','Jadalnia'];
const profiles={
1:['Dom Seniora Zielona Przystań','Warszawa','mazowieckie','Wilanów','Spokojny dom blisko miasta',7200,42,2019,12,'Kameralny dom opieki w zielonej części Wilanowa, zapewniający całodobowe wsparcie, opiekę pielęgniarską i indywidualny plan opieki przygotowany wspólnie z rodziną.','Mieszkańcy korzystają z ogrodu terapeutycznego, rehabilitacji i codziennych zajęć. Rodziny mogą odwiedzać bliskich każdego dnia.'],
2:['Rezydencja Pod Lipami','Kraków','małopolskie','Dębniki','Rodzinna atmosfera wśród starych lip',6800,36,2016,18,'Rezydencja w spokojnej części Krakowa specjalizuje się w opiece całodobowej i paliatywnej. Niewielkie zespoły opiekunów dobrze poznają zwyczaje każdego mieszkańca.','Własna kuchnia przygotowuje diety lekkostrawne i cukrzycowe. Zacieniony ogród sprzyja spotkaniom rodzin i odpoczynkowi.'],
3:['Przystań Dobra Jesień','Gdańsk','pomorskie','Oliwa','Opieka z nadmorskim spokojem',8100,48,2021,9,'Nowoczesna placówka w gdańskiej Oliwie łączy stałą opiekę medyczną z aktywizacją dopasowaną do możliwości seniora. Budynek jest dostępny dla osób z ograniczoną mobilnością.','Program obejmuje fizjoterapię, spacery i zajęcia pamięciowe. Bliskość parków ułatwia spokojny wypoczynek i częste odwiedziny.'],
4:['Centrum Opieki Harmonia','Wrocław','dolnośląskie','Krzyki','Kompleksowe wsparcie i rehabilitacja',6400,55,2018,25,'Centrum na wrocławskich Krzykach zapewnia opiekę całodobową, medyczną i paliatywną. Zespół wspiera osoby po udarach i z chorobami przewlekłymi.','Na miejscu działają sale rehabilitacyjne i gabinet zabiegowy. Rodziny regularnie otrzymują informacje o zdrowiu bliskiej osoby.'],
5:['Klub Seniora Słoneczny','Poznań','wielkopolskie','Jeżyce','Aktywny dzień, wieczór we własnym domu',4500,28,2020,7,'Dzienny dom dla samodzielnych seniorów, którzy chcą spędzać czas w dobrym towarzystwie i korzystać z bezpiecznego wsparcia w ciągu dnia.','Program obejmuje posiłki, gimnastykę, warsztaty i wyjścia kulturalne. Placówka organizuje również transport na terenie Poznania.'],
6:['Dom Opieki Leśne Zacisze','Białystok','podlaskie','Dojlidy','Cisza, zieleń i codzienne bezpieczeństwo',5900,32,2015,32,'Dom na obrzeżach Białegostoku oferuje opiekę całodobową w spokojnym, leśnym otoczeniu. Kameralna skala sprzyja bliskim relacjom z personelem.','Placówka prowadzi własną kuchnię i dostosowuje jadłospis do zaleceń lekarza. Teren spacerowy jest dostępny dla osób z ograniczoną mobilnością.'],
7:['Rezydencja Spokojny Port','Szczecin','zachodniopomorskie','Pogodno','Kameralna opieka na szczecińskim Pogodnie',7600,40,2017,14,'Rezydencja wspiera osoby wymagające opieki całodobowej i paliatywnej. Każdy mieszkaniec ma stałego opiekuna prowadzącego kontakt z rodziną.','Jasne pokoje, spokojna dzielnica i elastyczne godziny odwiedzin pomagają zachować codzienny kontakt z bliskimi.'],
8:['Dzienny Dom Blisko','Lublin','lubelskie','Czechów','Dobre dni w gronie innych osób',4200,30,2022,11,'Dzienna placówka na lubelskim Czechowie jest przeznaczona dla seniorów mieszkających we własnym domu, którzy potrzebują towarzystwa, posiłków i wsparcia w ciągu dnia.','Zespół prowadzi rehabilitację, treningi pamięci i zajęcia tematyczne. Możliwy jest dowóz seniora z Lublina i okolic.'],
9:['Senior Residence Parkowa','Łódź','łódzkie','Polesie','Miejski komfort przy zielonym parku',6100,46,2019,16,'Placówka na łódzkim Polesiu łączy dostęp do miejskich usług z ciszą pobliskiego parku. Zapewnia stałą pomoc opiekunów i pielęgniarek.','Mieszkańcy uczestniczą w zajęciach ruchowych, spotkaniach muzycznych i wspólnym planowaniu aktywności.'],
10:['Dom Spokojna Dolina','Katowice','śląskie','Ligota','Specjalistyczna opieka w spokojnej dzielnicy',6700,44,2014,10,'Dom w katowickiej Ligocie specjalizuje się w opiece nad osobami z chorobami przewlekłymi oraz w opiece paliatywnej.','Personel współpracuje z lekarzami i fizjoterapeutami, a plan wsparcia jest regularnie konsultowany z rodziną mieszkańca.'],
11:['Ośrodek Seniora Nad Brdą','Bydgoszcz','kujawsko-pomorskie','Bartodzieje','Aktywność i odpoczynek nad rzeką',5700,34,2018,8,'Ośrodek dzienny i medyczny w Bydgoszczy pomaga utrzymać samodzielność poprzez rehabilitację, posiłki i codzienną aktywizację.','Położenie blisko terenów nadrzecznych pozwala organizować bezpieczne spacery oraz zajęcia na świeżym powietrzu.'],
12:['Rezydencja Warmińska','Olsztyn','warmińsko-mazurskie','Likusy','Domowa opieka w otoczeniu jezior',6500,38,2016,13,'Rezydencja w olsztyńskich Likusach oferuje całodobowy pobyt w cichym otoczeniu, niedaleko jeziora. Pokoje są przystosowane do potrzeb osób starszych.','Placówka stawia na spokojny rytm dnia, domową kuchnię oraz zajęcia dopasowane do zainteresowań mieszkańców.'],
13:['Dom Seniora Podkarpacie','Rzeszów','podkarpackie','Drabinianka','Nowoczesna opieka blisko rodziny',5800,50,2020,9,'Rzeszowski dom zapewnia opiekę medyczną i całodobową w nowoczesnym budynku bez barier. Każde piętro ma własną strefę wypoczynku.','Rehabilitanci prowadzą zajęcia indywidualne, a rodziny otrzymują bieżące informacje o bliskiej osobie.'],
14:['Opolski Dom Opieki','Opole','opolskie','Zaodrze','Codzienne wsparcie w kameralnym domu',6200,29,2013,7,'Kameralna placówka na opolskim Zaodrzu przyjmuje seniorów na pobyt stały i dzienny. Niewielka liczba mieszkańców pozwala zachować domowy charakter.','Własna kuchnia, pokoje jednoosobowe i regularne zajęcia integracyjne tworzą przewidywalne, bezpieczne środowisko.'],
15:['Przystań Świętokrzyska','Kielce','świętokrzyskie','Baranówek','Opieka i ruch u podnóża wzgórz',5600,37,2017,11,'Placówka na kieleckim Baranówku oferuje całodobową opiekę i rehabilitację dla osób po hospitalizacji oraz wymagających stałego wsparcia.','Ogród z łagodnymi alejkami służy spacerom i terapii ruchowej. Jadłospis uwzględnia diety lecznicze.'],
16:['Zielonogórski Klub Seniora','Zielona Góra','lubuskie','Centrum','Towarzystwo, ruch i nowe zainteresowania',4300,26,2021,6,'Klub dziennego pobytu wspiera samodzielnych mieszkańców Zielonej Góry, oferując bezpieczne miejsce spotkań, posiłki i pomoc opiekunów.','Program obejmuje gimnastykę, warsztaty cyfrowe, gry, wyjścia oraz odpoczynek w niewielkim ogrodzie.']};
function applyProfile(){let id=Number(new URLSearchParams(location.search).get('id'))||1,p=profiles[id]||profiles[1],[n,c,r,area,tag,price,people,year,dist,d1,d2]=p;document.title=`${n} — Blisko`;$('.crumbs').textContent=`${r} / ${c} / Domy opieki`;$('.intro h1').textContent=n;$('.place').textContent=`⌖ ${c}, ${area}　•　${dist} km od centrum`;$('.summary h2').textContent=tag;let paras=$$('.summary>p');paras[0].textContent=d1;paras[1].textContent=d2;$('.facts').innerHTML=`<span><b>${people}</b> mieszkańców</span><span><b>24/7</b> opieka</span><span><b>${year}</b> rok otwarcia</span><span><b>${dist} km</b> od centrum</span>`;let prices=$$('.rooms footer b');prices[0].textContent=new Intl.NumberFormat('pl-PL').format(price+1200)+' zł';prices[1].textContent=new Intl.NumberFormat('pl-PL').format(price)+' zł';$('.contact-card>p').textContent=`Wyślij niezobowiązujące zapytanie do ${n}. Placówka skontaktuje się z Tobą, by omówić potrzeby bliskiej osoby.`}
function calendar(){let y=view.getFullYear(),m=view.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate(),today=new Date();$('#month').textContent=months[m]+' '+y;let html='';for(let i=0;i<first;i++)html+='<span></span>';for(let d=1;d<=total;d++){let dt=new Date(y,m,d),iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,free=dt>=new Date(today.getFullYear(),today.getMonth(),today.getDate())&&[1,3,5].includes(d%7);html+=`<button ${free?'':'disabled'} class="${selected===iso?'selected':''}" data-date="${iso}">${d}</button>`}$('#days').innerHTML=html;$$('[data-date]').forEach(b=>b.onclick=()=>{selected=b.dataset.date;$('#contactDate').value=selected;calendar();toast('Termin dodany do zapytania')})}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function showSlide(n){slide=(n+photos.length)%photos.length;$('#slideLabel').textContent=photos[slide];$('#modal').hidden=false;document.body.classList.add('locked')}
applyProfile();$('#prev').onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()-1,1);calendar()};$('#next').onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1);calendar()};$$('[data-room]').forEach(b=>b.onclick=()=>{$('[name=room]').value=b.dataset.room;$('#contactForm').scrollIntoView({behavior:'smooth'});toast('Wybrano: '+b.dataset.room)});$$('[data-photo]').forEach(b=>b.onclick=()=>showSlide(+b.dataset.photo));$('#close').onclick=()=>{$('#modal').hidden=true;document.body.classList.remove('locked')};$('#back').onclick=()=>showSlide(slide-1);$('#forward').onclick=()=>showSlide(slide+1);$('#save').onclick=e=>{e.currentTarget.classList.toggle('saved');e.currentTarget.textContent=e.currentTarget.classList.contains('saved')?'♥ Zapisano':'♡ Zapisz placówkę';toast(e.currentTarget.classList.contains('saved')?'Dodano do zapisanych':'Usunięto z zapisanych')};$('#visit').onclick=()=>{$('#contactForm').scrollIntoView({behavior:'smooth'});$('[name=message]').value='Chcę umówić bezpłatną wizytę w placówce.'};$('#contactForm').onsubmit=e=>{e.preventDefault();e.currentTarget.innerHTML='<div class="success"><b>✓</b><h3>Dziękujemy za zapytanie</h3><p>Placówka otrzymała Twoją wiadomość. W prototypie formularz nie wysyła prawdziwych danych.</p></div>'};$('#contactDate').min=new Date().toISOString().slice(0,10);calendar();

